# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applet', models.CharField(max_length=15)),
                ('entity_id', models.IntegerField()),
                ('view', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('applet', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=False)),
                ('viewing', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=5)),
                ('entities', models.CharField(max_length=30)),
                ('clouds', models.CharField(max_length=100)),
                ('favorites', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=10)),
                ('related_pars', models.CharField(max_length=100)),
                ('related_sibs', models.CharField(max_length=100)),
                ('related_subs', models.CharField(max_length=100)),
                ('story', models.CharField(max_length=30)),
                ('community', models.CharField(max_length=30)),
                ('interest', models.CharField(max_length=30)),
                ('business', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('applet', models.CharField(max_length=15)),
                ('folder', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
